### ISSUE TITLE
[Question] Can the docker service be used in a similar manner as a docker-compose yml file?

### ISSUE THREAD

**Issue by GSasu** [stsvilik/wdio-docker-service#47]
Hi,

I am interested if the docker service is able to run a docker-compose file or if I can build a setup with multiple images similar to the following docker-compose.yml file.

```
version: '3'
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid
    volumes:
      - .{$PWD}
      - ./docker:/etc/selenoid/
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/video:/opt/selenoid/video
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/opt/selenium/video
    command: [
      "-limit",  "12",
      "-conf", "/etc/selenoid/browsers.json",
      "-video-output-dir", "/opt/selenoid/video"
    ]
    ports:
      - "4444:4444"
    restart: always
  selenoid-ui:
    network_mode: bridge
    image: "aerokube/selenoid-ui"
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
    restart: always
  chrome:
    image: selenoid/vnc:chrome_73.0
    network_mode: bridge
    links:
      - selenoid
    volumes:
      - .{$PWD}
      - /dev/shm:/dev/shm
    depends_on:
      - selenoid
    restart: always
  firefox:
    image: selenoid/vnc:firefox_66.0
    network_mode: bridge
    links:
      - selenoid
    volumes:
      - .{$PWD}
      - /dev/shm:/dev/shm
    depends_on:
      - selenoid
    restart: always
```

I'm asking this because I am more used to docker-compose than docker run and wanted to know if I need to look into transforming my yml file into a single docker run command or not.

Thank you in advance
