### ISSUE TITLE
extra_host option needed

### ISSUE THREAD

**Issue by ssfxate** [stsvilik/wdio-docker-service#90]
Hey, how can I add `extra_hosts` to `dockerOptions`?

When I'm using docker-compose, it looks like this. How can I add this parameter into wdio config options for `wdio-docker-service`?
```yaml
    image: myimage
    shm_size: 2g
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    volumes:
      - ./uploadImages/:/uploadImages
    ports:
      - 5900:5900
    extra_hosts:
      - "nginx:172.17.0.1"
```
